apiVersion: v2
name: kng-web-base
description: A Helm chart for Kubernetes at kng web base

maintainers:
  - name: Erika Vacacela Belduma
    email: evacacela@ec.krugercorp.com

annotations:
  lifecycle.cattle.io/create.helm-controller_c-wbskn: true

keywords:
  - nginx
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0-snapshot
icon: https://bitbucket.org/corporacionfavorita/kng-web-base/raw/a1d5ee2aa7fed5972fa073bff5e2d96b0f0c2c48/ci/helm/icon.png

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0-SNAPSHOT

dependencies:
  - name: deployment
    version: 1.0.0
    repository: https://cf1hlmnxs.cfavorita.net/repository/helm-base/
    condition: deployment
